name: CI
on: [push, pull_request]

jobs:
    check:
        name: Mai
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  submodules: recursive

            - uses: actions/setup-node@v2
              with:
                  node-version: "16.14.0"

            - name: Install npm dependencies
              run: yarn install

            - name: Run TSC
              run: yarn build
